### ISSUE TITLE
Is SpaceBuild dead?  (Hopefully not anymore!)

### ISSUE THREAD

**Issue by Benie76** [spacebuild/spacebuild#77] opened 2014-10-29 23:35 UTC
So, SpaceBuild 4 is still a WIP, yet I feel it's dead as the files haven't been touched for two years. Plus, SpaceBuild 3 is buggy with Gmod 13.
Mainly, SBEP seats seem to float when AdvDuped, yet normal seats are fine. And also I'm getting errors selecting the Atmospheric Probe.

Lastly, when saving my game and loading, all SpaceBuild props disappeared and my ship is completely de-welded.
If SpaceBuild isn't dead and people haven't moved on from it, I hope to see a response to this. I'll provide console logs, but only if this gets responded to in the form of a helpful reply.

**Comment by Sycend** [comment] 2015-02-02 08:58
-> SpaceEngineers is the new Space Build

spaceengineersgame.com

**Comment by TyanColte** [comment] 2015-02-03 04:52
Unfortunately I believe spacebuild in its original form is dead. I still have a working fork of sb3 along with sbep but i freak it's been so long since I played it that the updates to gmod may have outdated it as well. RIP spacebuild. My only regret is not learning enough Lua to be able to work on it myself. If try to revive it when I got the time. I can piddle around here and there with the code understanding maybe half of it at least enough to change what I wanted to. But the logic of it still eludes me. I hope someone can revive it and make it better than ever but I highly doubt that day will every come.

**Comment by TyanColte** [comment] 2015-02-03 04:53
Freak it's supposed to be fear. Not sure why github doesn't have a way to edit comments.

**Comment by awilliamson** [comment] 2015-02-07 00:57
The issue wasn't for lack of programmers. It's that some projects run their cycle, the community isn't there and better alternatives with more activity replace it. GMod isn't the same place it once was, more and more children are getting the game and you begin to notice more of a shift towards less 'build' based activities.

It's sad but also true. Spacebuild 4 was under development, but fell through for one reason or another. If you really really want a space based Gamemode under GMod, I'd recommend Divinity 2, the development is solid, really good, and development is active with an active player base.

**Comment by immibis** [comment] 2015-03-31 21:35
The SB2 code in this repository still mostly works. No idea about SB3, I didn't try that.

But if it's not *broken*, then it must be dead because everyone got bored of it.

**Comment by selekton99** [comment] 2015-04-01 01:59
Hey @awilliamson Guess what came up on my maths task? Quaternions hahaha

**Comment by SnakeSVx** [comment] 2015-11-17 10:06
As awilliamson said, there is no community anymore for this, a lot of the people on garry'smod went their way and want other types of gamemodes to play. People that still want to play it can either play on some of the servers that are still there and active. Or play other more focused games like space engineers (or similar). 

In short, problems with certain people and the lack of community is what took the development of spacebuild down.

**Comment by festro** [comment] 2016-03-21 06:35
that's horrible This was the only worthwhile game mode and the main reason reason for the discovery of my space sandbox preference

**Comment by awilliamson** [comment] 2016-03-21 19:28
@festro Sadly life moves on. We're all working on different things and all have the daily grind to complete. There are other space based gamemodes coming to GarrysMod, some of them are absolutely fantastic. It takes a lot of dedication from a lot of people to make something successful, and there's just not the community wanting to play SpaceBuild anymore.

I personally don't have the time to commit to GMod projects. I barely play any games any more, I haven't even contributed to Starfall in months. I'm too busy with academia and setting things up for the future. But such large projects require the continuous input from developers and the community, which I just can't afford at the moment.

**Comment by generalwrex** [comment] 2016-03-21 20:36
A lot of us that used to play Gmod don't have too much time on our hands anymore sadly, but anyone can fork out the repo and send in some pull requests to keep it alive ;)

**Comment by festro** [comment] 2016-03-26 10:48
I really wish I had the attention span to learn coding. Spacebuild is something that deserves to be immortalized maybe with GMod 2 it will be touched up and included SB had much more purpose in gmod than ttt. still don't know how that won its way into included gamemodes

**Comment by TheMerkyShadow** [comment] 2016-05-18 17:31
Im lurking in the corner on JAF sb3.
Head developer and experienced lua coder.
Ive noticed a spike within the recent months but as you would expect the player base is crawling with people who have no idea to play and ask me to help. But I believe the gamemode is definitely not dead. Just not as popular as it once was.

**Comment by generalwrex** [comment] 2016-05-18 18:34
It's one of those Gamemodes that will always be working somewhere. It's still the father of all space in Garry's Mod. 

I *might* (I'm stressing might pretty far) start coding on SB again if I ever actually get time.  If I do I would like people to request to merge in their fixes that have accumulated over time into the main repository here. Lets see if we can get others to make some pull requests too!

**Comment by TheMerkyShadow** [comment] 2016-05-18 19:05
Thank You, generalwrex is correct.
If we get some people involved too make pull requests that would be amazing. Glad someone else is out there who knows lua and would help contribute to making the gamemode even better. That being said 
If anyone's interested friend me on steam we can iron out some well known bugs.

**Comment by awilliamson** [comment] 2016-05-18 19:30
It would be nice, but it's the community really. It's usually the cause of project death. Things diverge, people gain their own agenda, and thus don't wish to push back upstream. I think it's possible we've had our time, and should be glad that communities still exist around what we worked on.

**Comment by generalwrex** [comment] 2016-05-18 19:36
Yeah, I started coding Lua again, I *might* (and i'm stressing that word as far as it can go,) work on a little SB again.  It might be stressed less if anyone else wants to join in and make some pull requests ;)

**Comment by awilliamson** [comment] 2016-05-18 20:20
@generalwrex You're more than welcome to take the preliminary work I did on SB4. Essentially a from-scratch gamemode implementing core concepts behind spacebuild. This was work undertaken with @SnakeSVx nearly 2 years ago now ( Ugh, time flies :C )

**Comment by generalwrex** [comment] 2016-05-18 23:26
I updated the readme with today being the revival date, this should have brought it back to the front of the network browser for people to see, we might get more people ;)

**Comment by festro** [comment] 2016-05-19 14:31
really look forward to the revival of SB:)

**Comment by Sycend** [comment] 2016-05-19 15:59
Just check this out. For me its SB as Standalone.
www.spaceengineersgame.com

**Comment by generalwrex** [comment] 2016-05-19 18:00
@Sycend SpaceEngineers is great, but it's not spacebuild.

**Comment by generalwrex** [comment] 2016-06-01 02:45
I'm going to close this as it's most definitely not dead anymore ;)

**Closed by generalwrex** 2016-06-01 02:45 UTC
Labels: Conversation, question
